#python ood.py --m baseline --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_AK_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex AK --nc 7 --dv 1  > results/isic/panelD/AK/baseline.txt
python ood.py --m baseline --mcdo 20 --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_AK_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex AK --nc 7 --dv 1  > results/isic/panelD/AK/baseline_mcdo.txt
#python ood.py --m odin --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_AK_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex AK --nc 7 --dv 1  > results/isic/panelD/AK/odin.txt
#python ood.py --m mahalanobis --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_AK_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex AK --nc 7 --dv 1  --bs 20  > results/isic/panelD/AK/mahalanobis.txt
#python ood.py --m rotation --mc /raid/ferles/checkpoints/isic_classifiers/rot_isic-_AK-best-model.pth --in isic --val imagenet --out isic --ex AK --nc 7 --dv 1  --bs 1 > results/isic/panelD/AK/rotation.txt
#python ood.py --m generalizedodin --mc /raid/ferles/checkpoints/isic_classifiers/GenOdinISICAK-best-model.pth --in isic --val imagenet --out isic --ex AK --nc 7 --dv 1  > results/isic/panelD/AK/generalizedodin.txt

#python ood.py --m baseline --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_BCC_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex BCC --nc 7 --dv 1  > results/isic/panelD/BCC/baseline.txt
python ood.py --m baseline --mcdo 20 --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_BCC_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex BCC --nc 7 --dv 1  > results/isic/panelD/BCC/baseline_mcdo.txt
#python ood.py --m odin --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_BCC_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex BCC --nc 7 --dv 1  > results/isic/panelD/BCC/odin.txt
#python ood.py --m mahalanobis --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_BCC_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex BCC --nc 7 --dv 1  --bs 20  > results/isic/panelD/BCC/mahalanobis.txt
#python ood.py --m rotation --mc /raid/ferles/checkpoints/isic_classifiers/rot_isic-_BCC-best-model.pth --in isic --val imagenet --out isic --ex BCC --nc 7 --dv 1  --bs 1 > results/isic/panelD/BCC/rotation.txt
#python ood.py --m generalizedodin --mc /raid/ferles/checkpoints/isic_classifiers/GenOdinISIC_BCC-best-model.pth --in isic --val imagenet --out isic --ex BCC --nc 7 --dv 1  > results/isic/panelD/BCC/generalizedodin.txt

#python ood.py --m baseline --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_BKL_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex BKL --nc 7 --dv 1  > results/isic/panelD/BKL/baseline.txt
python ood.py --m baseline --mcdo 20 --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_BKL_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex BKL --nc 7 --dv 1  > results/isic/panelD/BKL/baseline_mcdo.txt
#python ood.py --m odin --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_BKL_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex BKL --nc 7 --dv 1  > results/isic/panelD/BKL/odin.txt
#python ood.py --m mahalanobis --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_BKL_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex BKL --nc 7 --dv 1  --bs 20  > results/isic/panelD/BKL/mahalanobis.txt
#python ood.py --m rotation --mc /raid/ferles/checkpoints/isic_classifiers/rot_isic-_BKL-best-model.pth --in isic --val imagenet --out isic --ex BKL --nc 7 --dv 1  --bs 1 > results/isic/panelD/BKL/rotation.txt
#python ood.py --m generalizedodin --mc /raid/ferles/checkpoints/isic_classifiers/GenOdinISIC_BKL-best-model.pth --in isic --val imagenet --out isic --ex BKL --nc 7 --dv 1  > results/isic/panelD/BKL/generalizedodin.txt

#python ood.py --m baseline --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_DF_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex DF --nc 7 --dv 1  > results/isic/panelD/DF/baseline.txt
python ood.py --m baseline --mcdo 20 --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_DF_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex DF --nc 7 --dv 1  > results/isic/panelD/DF/baseline_mcdo.txt
#python ood.py --m odin --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_DF_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex DF --nc 7 --dv 1  > results/isic/panelD/DF/odin.txt
#python ood.py --m mahalanobis --mc /raid/ferles/checkpoints/isic_classifiers/custom_exclude_DF_step_lr_cutout_eb0-best-model.pth --in isic --val imagenet --out isic --ex DF --nc 7 --dv 1  --bs 20  > results/isic/panelD/DF/mahalanobis.txt
#python ood.py --m rotation --mc /raid/ferles/checkpoints/isic_classifiers/rot_isic-_DF-best-model.pth --in isic --val imagenet --out isic --ex DF --nc 7 --dv 1  --bs 1 > results/isic/panelD/DF/rotation.txt
#python ood.py --m generalizedodin --mc /raid/ferles/checkpoints/isic_classifiers/GenOdinISIC_DF-best-model.pth --in isic --val imagenet --out isic --ex DF --nc 7 --dv 1  > results/isic/panelD/DF/generalizedodin.txt